export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const REGISTER_SEARCH_TERM = 'REGISTER_SEARCH_TERM';
export const REGISTER_SEARCH_LOCATION= 'REGISTER_SEARCH_LOCATION';
export const EXECUTE_SEARCH = 'EXECUTE_SEARCH';
// watson
export const FETCH_WATSON = 'FETCH_WATSON';
export const FETCH_WATSON_SUCCESS = 'FETCH_WATSON_SUCCESS';
export const FETCH_WATSON_FAILURE = 'FETCH_WATSON_FAILURE';

// yelp
export const FETCH_YELP = 'FETCH_YELP';
export const FETCH_YELP_SUCCESS = 'FETCH_YELP_SUCCESS';
export const FETCH_YELP_FAILURE = 'FETCH_YELP_FAILURE';

// news
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

// youtube
export const FETCH_YOUTUBE = 'FETCH_YOUTUBE';
export const FETCH_YOUTUBE_SUCCESS = 'FETCH_YOUTUBE_SUCCESS';
export const FETCH_YOUTUBE_FAILURE = 'FETCH_YOUTUBE_FAILURE';

export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const RECIPES_RETURNED = 'RECIPES_RETURNED';
